version: '3.9'
services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  lavalink:
    image: jockerider199/lavalink:latest
    build:
      context: .
      dockerfile: Dockerfile.Lavalink
    restart: unless-stopped
    ports:
      - "2333:2333"
  bot:
    image: jockerider199/knl-bot:latest
    build:
      context: .
      dockerfile: Dockerfile.Bot
    depends_on:
      db:
        condition: service_healthy
      lavalink:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CONTAINER=TRUE